version: '{build}'
image:
- Visual Studio 2017
# - Visual Studio 2015
configuration: Debug
platform: Any CPU
environment:
  PLATFORM: Any CPU
  BuildPLATFORM: Any CPU
  BuildConfiguration: Debug
  configuration: Debug
branches:
  only:
  - devel
build_script:
- cmd: >-
    dotnet restore RDotNet.ns2.sln

    dotnet build --configuration Debug --no-restore  RDotNet.ns2.sln

test_script:
- cmd: >-
    dotnet test RDotNet.Tests/RDotNet.Tests.csproj

    dotnet test RDotNet.FSharp.Tests/RDotNet.FSharp.Tests.fsproj
