version: '{build}'
image:
- Visual Studio 2017
# - Visual Studio 2015
configuration: Debug
platform: Any CPU
environment:
  matrix:
  - PLATFORM: x64
  # - PLATFORM: x86
branches:
  only:
  - devel
build_script:
- cmd: >-
    dotnet build --configuration Debug --no-restore  RDotNet.ns2.sln

    # dotnet restore RDotNet.ns2.sln

    #msbuild RDotNet.ns2.sln /p:Platform="Any CPU" /p:Configuration=Debug /consoleloggerparameters:ErrorsOnly

test_script:
- cmd: >-
    dotnet test RDotNet.Tests/RDotNet.Tests.csproj

    dotnet test RDotNet.FSharp.Tests/RDotNet.FSharp.Tests.fsproj
