language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

branches:
  only:
  - master
  - testing

script:
- dotnet restore RDotNet.Tests.sln
- dotnet build --configuration Debug --no-restore  RDotNet.Tests.sln
- dotnet test RDotNet.Tests/RDotNet.Tests.csproj
- dotnet test RDotNet.FSharp.Tests/RDotNet.FSharp.Tests.fsproj
