host: 127.0.0.1 

url: "http://jmp75.github.io/rdotnet"

feedback_email: false

sidebar_accordion: true

disqus_shortname: false # idrbwjekyll

google_analytics: UA-65793394-1 # false 

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: pygments

print: false

floating_nav: true

# suffix: index.html

exclude: 
  - _drafts
  - bower_components
  - .idea 
  - _site

permalink: :title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      search: false
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      tooltip: true
      search: true

sass:
    sass_dir: _sass

collections:
  tooltips:
    output: true
